//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8662
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmsPanelTooska;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace = "tempuri.org")]

namespace tempuri.org
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    public class ArrayOfLong : System.Collections.Generic.List<long>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://tempuri.org/")]
    public partial class Messages : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long MessageIDField;
        
        private string RecipientNumberField;
        
        private string SenderNumberField;
        
        private string BodyField;
        
        private string ReceiveDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecipientNumber
        {
            get
            {
                return this.RecipientNumberField;
            }
            set
            {
                this.RecipientNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderNumber
        {
            get
            {
                return this.SenderNumberField;
            }
            set
            {
                this.SenderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReceiveDate
        {
            get
            {
                return this.ReceiveDateField;
            }
            set
            {
                this.ReceiveDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendType", Namespace="http://tempuri.org/")]
    public enum SendType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllNumbers = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RandomNumbers = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SortingNumbers = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo", Namespace="http://tempuri.org/")]
    public partial class RequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private string senderNumberField;
        
        private string messageField;
        
        private System.DateTime sendDateField;
        
        private int totalSmsField;
        
        private int priceField;
        
        private int statusField;
        
        private string statusDescriptionField;
        
        private tempuri.org.RequestDelivery[] deliveryReportField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string senderNumber
        {
            get
            {
                return this.senderNumberField;
            }
            set
            {
                this.senderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime sendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int totalSms
        {
            get
            {
                return this.totalSmsField;
            }
            set
            {
                this.totalSmsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string statusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public tempuri.org.RequestDelivery[] deliveryReport
        {
            get
            {
                return this.deliveryReportField;
            }
            set
            {
                this.deliveryReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDelivery", Namespace="http://tempuri.org/")]
    public partial class RequestDelivery : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long statusIdField;
        
        private long statusCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long statusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long statusCount
        {
            get
            {
                return this.statusCountField;
            }
            set
            {
                this.statusCountField = value;
            }
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendSMSRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
    public SendSMSRequestBody Body;
    
    public SendSMSRequest()
    {
    }
    
    public SendSMSRequest(SendSMSRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class SendSMSResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.ArrayOfLong SendSMSResult;
    
    public SendSMSResponseBody()
    {
    }
    
    public SendSMSResponseBody(tempuri.org.ArrayOfLong SendSMSResult)
    {
        this.SendSMSResult = SendSMSResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetMessageStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatus", Namespace="http://tempuri.org/", Order=0)]
    public GetMessageStatusRequestBody Body;
    
    public GetMessageStatusRequest()
    {
    }
    
    public GetMessageStatusRequest(GetMessageStatusRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetMessageStatusRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public tempuri.org.ArrayOfLong MessageIDs;
    
    public GetMessageStatusRequestBody()
    {
    }
    
    public GetMessageStatusRequestBody(string username, string password, tempuri.org.ArrayOfLong MessageIDs)
    {
        this.username = username;
        this.password = password;
        this.MessageIDs = MessageIDs;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetMessageStatusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatusResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetMessageStatusResponseBody Body;
    
    public GetMessageStatusResponse()
    {
    }
    
    public GetMessageStatusResponse(GetMessageStatusResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetMessageStatusResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.ArrayOfInt GetMessageStatusResult;
    
    public GetMessageStatusResponseBody()
    {
    }
    
    public GetMessageStatusResponseBody(tempuri.org.ArrayOfInt GetMessageStatusResult)
    {
        this.GetMessageStatusResult = GetMessageStatusResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CheckMessageIDsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMessageIDs", Namespace="http://tempuri.org/", Order=0)]
    public CheckMessageIDsRequestBody Body;
    
    public CheckMessageIDsRequest()
    {
    }
    
    public CheckMessageIDsRequest(CheckMessageIDsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CheckMessageIDsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public tempuri.org.ArrayOfLong checkingids;
    
    public CheckMessageIDsRequestBody()
    {
    }
    
    public CheckMessageIDsRequestBody(string username, string password, tempuri.org.ArrayOfLong checkingids)
    {
        this.username = username;
        this.password = password;
        this.checkingids = checkingids;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CheckMessageIDsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMessageIDsResponse", Namespace="http://tempuri.org/", Order=0)]
    public CheckMessageIDsResponseBody Body;
    
    public CheckMessageIDsResponse()
    {
    }
    
    public CheckMessageIDsResponse(CheckMessageIDsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CheckMessageIDsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.ArrayOfLong CheckMessageIDsResult;
    
    public CheckMessageIDsResponseBody()
    {
    }
    
    public CheckMessageIDsResponseBody(tempuri.org.ArrayOfLong CheckMessageIDsResult)
    {
        this.CheckMessageIDsResult = CheckMessageIDsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetReceiveMessagesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiveMessages", Namespace="http://tempuri.org/", Order=0)]
    public GetReceiveMessagesRequestBody Body;
    
    public GetReceiveMessagesRequest()
    {
    }
    
    public GetReceiveMessagesRequest(GetReceiveMessagesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetReceiveMessagesRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string destNumber;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public int isRead;
    
    public GetReceiveMessagesRequestBody()
    {
    }
    
    public GetReceiveMessagesRequestBody(string username, string password, string destNumber, int isRead)
    {
        this.username = username;
        this.password = password;
        this.destNumber = destNumber;
        this.isRead = isRead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetReceiveMessagesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiveMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetReceiveMessagesResponseBody Body;
    
    public GetReceiveMessagesResponse()
    {
    }
    
    public GetReceiveMessagesResponse(GetReceiveMessagesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetReceiveMessagesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.Messages[] GetReceiveMessagesResult;
    
    public GetReceiveMessagesResponseBody()
    {
    }
    
    public GetReceiveMessagesResponseBody(tempuri.org.Messages[] GetReceiveMessagesResult)
    {
        this.GetReceiveMessagesResult = GetReceiveMessagesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountForPostalCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountForPostalCode", Namespace="http://tempuri.org/", Order=0)]
    public GetCountForPostalCodeRequestBody Body;
    
    public GetCountForPostalCodeRequest()
    {
    }
    
    public GetCountForPostalCodeRequest(GetCountForPostalCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetCountForPostalCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string postalcode;
    
    public GetCountForPostalCodeRequestBody()
    {
    }
    
    public GetCountForPostalCodeRequestBody(string username, string password, string postalcode)
    {
        this.username = username;
        this.password = password;
        this.postalcode = postalcode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountForPostalCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountForPostalCodeResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetCountForPostalCodeResponseBody Body;
    
    public GetCountForPostalCodeResponse()
    {
    }
    
    public GetCountForPostalCodeResponse(GetCountForPostalCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetCountForPostalCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int GetCountForPostalCodeResult;
    
    public GetCountForPostalCodeResponseBody()
    {
    }
    
    public GetCountForPostalCodeResponseBody(int GetCountForPostalCodeResult)
    {
        this.GetCountForPostalCodeResult = GetCountForPostalCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendBulkSmsToPostalCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBulkSmsToPostalCode", Namespace="http://tempuri.org/", Order=0)]
    public SendBulkSmsToPostalCodeRequestBody Body;
    
    public SendBulkSmsToPostalCodeRequest()
    {
    }
    
    public SendBulkSmsToPostalCodeRequest(SendBulkSmsToPostalCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class SendBulkSmsToPostalCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string postalcode;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string originator;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string content;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public tempuri.org.SendType sendType;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
    public System.DateTime sendDate;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
    public int startIndex;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
    public int count;
    
    public SendBulkSmsToPostalCodeRequestBody()
    {
    }
    
    public SendBulkSmsToPostalCodeRequestBody(string username, string password, string postalcode, string originator, string content, tempuri.org.SendType sendType, System.DateTime sendDate, int startIndex, int count)
    {
        this.username = username;
        this.password = password;
        this.postalcode = postalcode;
        this.originator = originator;
        this.content = content;
        this.sendType = sendType;
        this.sendDate = sendDate;
        this.startIndex = startIndex;
        this.count = count;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendBulkSmsToPostalCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBulkSmsToPostalCodeResponse", Namespace="http://tempuri.org/", Order=0)]
    public SendBulkSmsToPostalCodeResponseBody Body;
    
    public SendBulkSmsToPostalCodeResponse()
    {
    }
    
    public SendBulkSmsToPostalCodeResponse(SendBulkSmsToPostalCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class SendBulkSmsToPostalCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public long SendBulkSmsToPostalCodeResult;
    
    public SendBulkSmsToPostalCodeResponseBody()
    {
    }
    
    public SendBulkSmsToPostalCodeResponseBody(long SendBulkSmsToPostalCodeResult)
    {
        this.SendBulkSmsToPostalCodeResult = SendBulkSmsToPostalCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetBulkRequestInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBulkRequestInfo", Namespace="http://tempuri.org/", Order=0)]
    public GetBulkRequestInfoRequestBody Body;
    
    public GetBulkRequestInfoRequest()
    {
    }
    
    public GetBulkRequestInfoRequest(GetBulkRequestInfoRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetBulkRequestInfoRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public long requestId;
    
    public GetBulkRequestInfoRequestBody()
    {
    }
    
    public GetBulkRequestInfoRequestBody(string username, string password, long requestId)
    {
        this.username = username;
        this.password = password;
        this.requestId = requestId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetBulkRequestInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBulkRequestInfoResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetBulkRequestInfoResponseBody Body;
    
    public GetBulkRequestInfoResponse()
    {
    }
    
    public GetBulkRequestInfoResponse(GetBulkRequestInfoResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetBulkRequestInfoResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.RequestInfo GetBulkRequestInfoResult;
    
    public GetBulkRequestInfoResponseBody()
    {
    }
    
    public GetBulkRequestInfoResponseBody(tempuri.org.RequestInfo GetBulkRequestInfoResult)
    {
        this.GetBulkRequestInfoResult = GetBulkRequestInfoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetNewsListRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsList", Namespace="http://tempuri.org/", Order=0)]
    public GetNewsListRequestBody Body;
    
    public GetNewsListRequest()
    {
    }
    
    public GetNewsListRequest(GetNewsListRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetNewsListRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string username;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string password;
    
    public GetNewsListRequestBody()
    {
    }
    
    public GetNewsListRequestBody(string username, string password)
    {
        this.username = username;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetNewsListResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsListResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetNewsListResponseBody Body;
    
    public GetNewsListResponse()
    {
    }
    
    public GetNewsListResponse(GetNewsListResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetNewsListResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public News[] GetNewsListResult;
    
    public GetNewsListResponseBody()
    {
    }
    
    public GetNewsListResponseBody(News[] GetNewsListResult)
    {
        this.GetNewsListResult = GetNewsListResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IIv2SoapChannel : IV2Soap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Iv2SoapClient : System.ServiceModel.ClientBase<IV2Soap>, IV2Soap
{
    
    public Iv2SoapClient()
    {
    }
    
    public Iv2SoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Iv2SoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Iv2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Iv2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendSMSResponse IV2Soap.SendSMS(SendSMSRequest request)
    {
        return base.Channel.SendSMS(request);
    }
    
    public tempuri.org.ArrayOfLong SendSMS(string username, string password, tempuri.org.ArrayOfString senderNumbers, tempuri.org.ArrayOfString recipientNumbers, tempuri.org.ArrayOfString messageBodies, tempuri.org.ArrayOfString sendDate, tempuri.org.ArrayOfInt messageClasses, tempuri.org.ArrayOfLong checkingMessageIds)
    {
        SendSMSRequest inValue = new SendSMSRequest();
        inValue.Body = new SendSMSRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.senderNumbers = senderNumbers;
        inValue.Body.recipientNumbers = recipientNumbers;
        inValue.Body.messageBodies = messageBodies;
        inValue.Body.sendDate = sendDate;
        inValue.Body.messageClasses = messageClasses;
        inValue.Body.checkingMessageIds = checkingMessageIds;
        SendSMSResponse retVal = ((IV2Soap)(this)).SendSMS(inValue);
        return retVal.Body.SendSMSResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetMessageStatusResponse IV2Soap.GetMessageStatus(GetMessageStatusRequest request)
    {
        return base.Channel.GetMessageStatus(request);
    }
    
    public tempuri.org.ArrayOfInt GetMessageStatus(string username, string password, tempuri.org.ArrayOfLong MessageIDs)
    {
        GetMessageStatusRequest inValue = new GetMessageStatusRequest();
        inValue.Body = new GetMessageStatusRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.MessageIDs = MessageIDs;
        GetMessageStatusResponse retVal = ((IV2Soap)(this)).GetMessageStatus(inValue);
        return retVal.Body.GetMessageStatusResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCreditResponse IV2Soap.GetCredit(GetCreditRequest request)
    {
        return base.Channel.GetCredit(request);
    }
    
    public double GetCredit(string username, string password)
    {
        GetCreditRequest inValue = new GetCreditRequest();
        inValue.Body = new GetCreditRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        GetCreditResponse retVal = ((IV2Soap)(this)).GetCredit(inValue);
        return retVal.Body.GetCreditResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CheckMessageIDsResponse IV2Soap.CheckMessageIDs(CheckMessageIDsRequest request)
    {
        return base.Channel.CheckMessageIDs(request);
    }
    
    public tempuri.org.ArrayOfLong CheckMessageIDs(string username, string password, tempuri.org.ArrayOfLong checkingids)
    {
        CheckMessageIDsRequest inValue = new CheckMessageIDsRequest();
        inValue.Body = new CheckMessageIDsRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.checkingids = checkingids;
        CheckMessageIDsResponse retVal = ((IV2Soap)(this)).CheckMessageIDs(inValue);
        return retVal.Body.CheckMessageIDsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetReceiveMessagesResponse IV2Soap.GetReceiveMessages(GetReceiveMessagesRequest request)
    {
        return base.Channel.GetReceiveMessages(request);
    }
    
    public tempuri.org.Messages[] GetReceiveMessages(string username, string password, string destNumber, int isRead)
    {
        GetReceiveMessagesRequest inValue = new GetReceiveMessagesRequest();
        inValue.Body = new GetReceiveMessagesRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.destNumber = destNumber;
        inValue.Body.isRead = isRead;
        GetReceiveMessagesResponse retVal = ((IV2Soap)(this)).GetReceiveMessages(inValue);
        return retVal.Body.GetReceiveMessagesResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCountForPostalCodeResponse IV2Soap.GetCountForPostalCode(GetCountForPostalCodeRequest request)
    {
        return base.Channel.GetCountForPostalCode(request);
    }
    
    public int GetCountForPostalCode(string username, string password, string postalcode)
    {
        GetCountForPostalCodeRequest inValue = new GetCountForPostalCodeRequest();
        inValue.Body = new GetCountForPostalCodeRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.postalcode = postalcode;
        GetCountForPostalCodeResponse retVal = ((IV2Soap)(this)).GetCountForPostalCode(inValue);
        return retVal.Body.GetCountForPostalCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendBulkSmsToPostalCodeResponse IV2Soap.SendBulkSmsToPostalCode(SendBulkSmsToPostalCodeRequest request)
    {
        return base.Channel.SendBulkSmsToPostalCode(request);
    }
    
    public long SendBulkSmsToPostalCode(string username, string password, string postalcode, string originator, string content, tempuri.org.SendType sendType, System.DateTime sendDate, int startIndex, int count)
    {
        SendBulkSmsToPostalCodeRequest inValue = new SendBulkSmsToPostalCodeRequest();
        inValue.Body = new SendBulkSmsToPostalCodeRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.postalcode = postalcode;
        inValue.Body.originator = originator;
        inValue.Body.content = content;
        inValue.Body.sendType = sendType;
        inValue.Body.sendDate = sendDate;
        inValue.Body.startIndex = startIndex;
        inValue.Body.count = count;
        SendBulkSmsToPostalCodeResponse retVal = ((IV2Soap)(this)).SendBulkSmsToPostalCode(inValue);
        return retVal.Body.SendBulkSmsToPostalCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBulkRequestInfoResponse IV2Soap.GetBulkRequestInfo(GetBulkRequestInfoRequest request)
    {
        return base.Channel.GetBulkRequestInfo(request);
    }
    
    public tempuri.org.RequestInfo GetBulkRequestInfo(string username, string password, long requestId)
    {
        GetBulkRequestInfoRequest inValue = new GetBulkRequestInfoRequest();
        inValue.Body = new GetBulkRequestInfoRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        inValue.Body.requestId = requestId;
        GetBulkRequestInfoResponse retVal = ((IV2Soap)(this)).GetBulkRequestInfo(inValue);
        return retVal.Body.GetBulkRequestInfoResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetNewsListResponse IV2Soap.GetNewsList(GetNewsListRequest request)
    {
        return base.Channel.GetNewsList(request);
    }
    
    public News[] GetNewsList(string username, string password)
    {
        GetNewsListRequest inValue = new GetNewsListRequest();
        inValue.Body = new GetNewsListRequestBody();
        inValue.Body.username = username;
        inValue.Body.password = password;
        GetNewsListResponse retVal = ((IV2Soap)(this)).GetNewsList(inValue);
        return retVal.Body.GetNewsListResult;
    }
}
