//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsPanelAlma.AlmaSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:smsserver", ConfigurationName="AlmaSms.smsserverPortType")]
    public interface smsserverPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message SendMultipleSMSRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="SendMultipleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmsPanelAlma.AlmaSms.SendMultipleSMSResponse SendMultipleSMS(SmsPanelAlma.AlmaSms.SendMultipleSMSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message SendSMSRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmsPanelAlma.AlmaSms.SendSMSResponse SendSMS(SmsPanelAlma.AlmaSms.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message GetCreditRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmsPanelAlma.AlmaSms.GetCreditResponse GetCredit(SmsPanelAlma.AlmaSms.GetCreditRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message GetStatusRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmsPanelAlma.AlmaSms.GetStatusResponse GetStatus(SmsPanelAlma.AlmaSms.GetStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class SendMultipleSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] fromNums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string[] toNums;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string[] messageContents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] messageTypes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string pass;
        
        public SendMultipleSMSRequest() {
        }
        
        public SendMultipleSMSRequest(string[] fromNums, string[] toNums, string[] messageContents, string[] messageTypes, string user, string pass) {
            this.fromNums = fromNums;
            this.toNums = toNums;
            this.messageContents = messageContents;
            this.messageTypes = messageTypes;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMSResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class SendMultipleSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendMultipleSMSResponse() {
        }
        
        public SendMultipleSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string fromNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string[] toNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string pass;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(string fromNum, string[] toNum, string messageContent, string messageType, string user, string pass) {
            this.fromNum = fromNum;
            this.toNum = toNum;
            this.messageContent = messageContent;
            this.messageType = messageType;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredit", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pass;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCreditResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string[] unique_ids;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(string user, string pass, string[] unique_ids) {
            this.user = user;
            this.pass = pass;
            this.unique_ids = unique_ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsserverPortTypeChannel : SmsPanelAlma.AlmaSms.smsserverPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsserverPortTypeClient : System.ServiceModel.ClientBase<SmsPanelAlma.AlmaSms.smsserverPortType>, SmsPanelAlma.AlmaSms.smsserverPortType {
        
        public smsserverPortTypeClient() {
        }
        
        public smsserverPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsserverPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserverPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserverPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanelAlma.AlmaSms.SendMultipleSMSResponse SmsPanelAlma.AlmaSms.smsserverPortType.SendMultipleSMS(SmsPanelAlma.AlmaSms.SendMultipleSMSRequest request) {
            return base.Channel.SendMultipleSMS(request);
        }
        
        public string SendMultipleSMS(string[] fromNums, string[] toNums, string[] messageContents, string[] messageTypes, string user, string pass) {
            SmsPanelAlma.AlmaSms.SendMultipleSMSRequest inValue = new SmsPanelAlma.AlmaSms.SendMultipleSMSRequest();
            inValue.fromNums = fromNums;
            inValue.toNums = toNums;
            inValue.messageContents = messageContents;
            inValue.messageTypes = messageTypes;
            inValue.user = user;
            inValue.pass = pass;
            SmsPanelAlma.AlmaSms.SendMultipleSMSResponse retVal = ((SmsPanelAlma.AlmaSms.smsserverPortType)(this)).SendMultipleSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanelAlma.AlmaSms.SendSMSResponse SmsPanelAlma.AlmaSms.smsserverPortType.SendSMS(SmsPanelAlma.AlmaSms.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string fromNum, string[] toNum, string messageContent, string messageType, string user, string pass) {
            SmsPanelAlma.AlmaSms.SendSMSRequest inValue = new SmsPanelAlma.AlmaSms.SendSMSRequest();
            inValue.fromNum = fromNum;
            inValue.toNum = toNum;
            inValue.messageContent = messageContent;
            inValue.messageType = messageType;
            inValue.user = user;
            inValue.pass = pass;
            SmsPanelAlma.AlmaSms.SendSMSResponse retVal = ((SmsPanelAlma.AlmaSms.smsserverPortType)(this)).SendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanelAlma.AlmaSms.GetCreditResponse SmsPanelAlma.AlmaSms.smsserverPortType.GetCredit(SmsPanelAlma.AlmaSms.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public string GetCredit(string user, string pass) {
            SmsPanelAlma.AlmaSms.GetCreditRequest inValue = new SmsPanelAlma.AlmaSms.GetCreditRequest();
            inValue.user = user;
            inValue.pass = pass;
            SmsPanelAlma.AlmaSms.GetCreditResponse retVal = ((SmsPanelAlma.AlmaSms.smsserverPortType)(this)).GetCredit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanelAlma.AlmaSms.GetStatusResponse SmsPanelAlma.AlmaSms.smsserverPortType.GetStatus(SmsPanelAlma.AlmaSms.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public string GetStatus(string user, string pass, string[] unique_ids) {
            SmsPanelAlma.AlmaSms.GetStatusRequest inValue = new SmsPanelAlma.AlmaSms.GetStatusRequest();
            inValue.user = user;
            inValue.pass = pass;
            inValue.unique_ids = unique_ids;
            SmsPanelAlma.AlmaSms.GetStatusResponse retVal = ((SmsPanelAlma.AlmaSms.smsserverPortType)(this)).GetStatus(inValue);
            return retVal.@return;
        }
    }
}
