//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="sms_webserviceBinding", Namespace="urn:sms_webservice")]
public partial class sms_webservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback sms_get_number_in_catOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_get_cat_listOperationCompleted;
    
    private System.Threading.SendOrPostCallback send_sms_all_arrayOperationCompleted;
    
    private System.Threading.SendOrPostCallback send_sms_arrayOperationCompleted;
    
    private System.Threading.SendOrPostCallback send_smsOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_postalcode_countOperationCompleted;
    
    private System.Threading.SendOrPostCallback is_number_in_blacklistOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_creditOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_user_infoOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_deliverOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_deliver_with_array_of_smsidOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_deliver_with_deliver_stateOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_add_numberOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_receive_listOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_receive_list_arrayOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_receive_change_readOperationCompleted;
    
    private System.Threading.SendOrPostCallback add_userOperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_send_bulk_5000OperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_count_bulk_5000OperationCompleted;
    
    private System.Threading.SendOrPostCallback sms_count_bank_5000OperationCompleted;
    
    /// <remarks/>
    public sms_webservice() {
        this.Url = "http://www.textsms.ir:80/webservice/smsService.php";
    }
    
    /// <remarks/>
    public event sms_get_number_in_catCompletedEventHandler sms_get_number_in_catCompleted;
    
    /// <remarks/>
    public event sms_get_cat_listCompletedEventHandler sms_get_cat_listCompleted;
    
    /// <remarks/>
    public event send_sms_all_arrayCompletedEventHandler send_sms_all_arrayCompleted;
    
    /// <remarks/>
    public event send_sms_arrayCompletedEventHandler send_sms_arrayCompleted;
    
    /// <remarks/>
    public event send_smsCompletedEventHandler send_smsCompleted;
    
    /// <remarks/>
    public event sms_postalcode_countCompletedEventHandler sms_postalcode_countCompleted;
    
    /// <remarks/>
    public event is_number_in_blacklistCompletedEventHandler is_number_in_blacklistCompleted;
    
    /// <remarks/>
    public event sms_creditCompletedEventHandler sms_creditCompleted;
    
    /// <remarks/>
    public event sms_user_infoCompletedEventHandler sms_user_infoCompleted;
    
    /// <remarks/>
    public event sms_deliverCompletedEventHandler sms_deliverCompleted;
    
    /// <remarks/>
    public event sms_deliver_with_array_of_smsidCompletedEventHandler sms_deliver_with_array_of_smsidCompleted;
    
    /// <remarks/>
    public event sms_deliver_with_deliver_stateCompletedEventHandler sms_deliver_with_deliver_stateCompleted;
    
    /// <remarks/>
    public event sms_add_numberCompletedEventHandler sms_add_numberCompleted;
    
    /// <remarks/>
    public event sms_receive_listCompletedEventHandler sms_receive_listCompleted;
    
    /// <remarks/>
    public event sms_receive_list_arrayCompletedEventHandler sms_receive_list_arrayCompleted;
    
    /// <remarks/>
    public event sms_receive_change_readCompletedEventHandler sms_receive_change_readCompleted;
    
    /// <remarks/>
    public event add_userCompletedEventHandler add_userCompleted;
    
    /// <remarks/>
    public event sms_send_bulk_5000CompletedEventHandler sms_send_bulk_5000Completed;
    
    /// <remarks/>
    public event sms_count_bulk_5000CompletedEventHandler sms_count_bulk_5000Completed;
    
    /// <remarks/>
    public event sms_count_bank_5000CompletedEventHandler sms_count_bank_5000Completed;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_get_number_in_cat", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_get_number_in_cat")]
    public string sms_get_number_in_cat(string username, string password, int catid) {
        object[] results = this.Invoke("sms_get_number_in_cat", new object[] {
                    username,
                    password,
                    catid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_get_number_in_cat(string username, string password, int catid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_get_number_in_cat", new object[] {
                    username,
                    password,
                    catid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_get_number_in_cat(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_get_number_in_catAsync(string username, string password, int catid) {
        this.sms_get_number_in_catAsync(username, password, catid, null);
    }
    
    /// <remarks/>
    public void sms_get_number_in_catAsync(string username, string password, int catid, object userState) {
        if ((this.sms_get_number_in_catOperationCompleted == null)) {
            this.sms_get_number_in_catOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_get_number_in_catOperationCompleted);
        }
        this.InvokeAsync("sms_get_number_in_cat", new object[] {
                    username,
                    password,
                    catid}, this.sms_get_number_in_catOperationCompleted, userState);
    }
    
    private void Onsms_get_number_in_catOperationCompleted(object arg) {
        if ((this.sms_get_number_in_catCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_get_number_in_catCompleted(this, new sms_get_number_in_catCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_get_cat_list", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_get_cat_list")]
    public string sms_get_cat_list(string username, string password) {
        object[] results = this.Invoke("sms_get_cat_list", new object[] {
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_get_cat_list(string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_get_cat_list", new object[] {
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_get_cat_list(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_get_cat_listAsync(string username, string password) {
        this.sms_get_cat_listAsync(username, password, null);
    }
    
    /// <remarks/>
    public void sms_get_cat_listAsync(string username, string password, object userState) {
        if ((this.sms_get_cat_listOperationCompleted == null)) {
            this.sms_get_cat_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_get_cat_listOperationCompleted);
        }
        this.InvokeAsync("sms_get_cat_list", new object[] {
                    username,
                    password}, this.sms_get_cat_listOperationCompleted, userState);
    }
    
    private void Onsms_get_cat_listOperationCompleted(object arg) {
        if ((this.sms_get_cat_listCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_get_cat_listCompleted(this, new sms_get_cat_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#send_sms_all_array", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("send_sms_all_array")]
    public string send_sms_all_array(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, string date, string request_uniqueid) {
        object[] results = this.Invoke("send_sms_all_array", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsend_sms_all_array(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, string date, string request_uniqueid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("send_sms_all_array", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsend_sms_all_array(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void send_sms_all_arrayAsync(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, string date, string request_uniqueid) {
        this.send_sms_all_arrayAsync(username, password, sender_number, receiver_number, note, ersal_flash, onlysend, date, request_uniqueid, null);
    }
    
    /// <remarks/>
    public void send_sms_all_arrayAsync(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, string date, string request_uniqueid, object userState) {
        if ((this.send_sms_all_arrayOperationCompleted == null)) {
            this.send_sms_all_arrayOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_sms_all_arrayOperationCompleted);
        }
        this.InvokeAsync("send_sms_all_array", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid}, this.send_sms_all_arrayOperationCompleted, userState);
    }
    
    private void Onsend_sms_all_arrayOperationCompleted(object arg) {
        if ((this.send_sms_all_arrayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.send_sms_all_arrayCompleted(this, new send_sms_all_arrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#send_sms_array", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("send_sms_array")]
    public string send_sms_array(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid) {
        object[] results = this.Invoke("send_sms_array", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsend_sms_array(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("send_sms_array", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsend_sms_array(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void send_sms_arrayAsync(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid) {
        this.send_sms_arrayAsync(username, password, sender_number, receiver_number, note, ersal_flash, onlysend, date, request_uniqueid, null);
    }
    
    /// <remarks/>
    public void send_sms_arrayAsync(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid, object userState) {
        if ((this.send_sms_arrayOperationCompleted == null)) {
            this.send_sms_arrayOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_sms_arrayOperationCompleted);
        }
        this.InvokeAsync("send_sms_array", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid}, this.send_sms_arrayOperationCompleted, userState);
    }
    
    private void Onsend_sms_arrayOperationCompleted(object arg) {
        if ((this.send_sms_arrayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.send_sms_arrayCompleted(this, new send_sms_arrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#send_sms", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("send_sms")]
    public string send_sms(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid) {
        object[] results = this.Invoke("send_sms", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsend_sms(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("send_sms", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsend_sms(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void send_smsAsync(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid) {
        this.send_smsAsync(username, password, sender_number, receiver_number, note, ersal_flash, onlysend, date, request_uniqueid, null);
    }
    
    /// <remarks/>
    public void send_smsAsync(string username, string password, string sender_number, string receiver_number, string note, string ersal_flash, string onlysend, int date, string request_uniqueid, object userState) {
        if ((this.send_smsOperationCompleted == null)) {
            this.send_smsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_smsOperationCompleted);
        }
        this.InvokeAsync("send_sms", new object[] {
                    username,
                    password,
                    sender_number,
                    receiver_number,
                    note,
                    ersal_flash,
                    onlysend,
                    date,
                    request_uniqueid}, this.send_smsOperationCompleted, userState);
    }
    
    private void Onsend_smsOperationCompleted(object arg) {
        if ((this.send_smsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.send_smsCompleted(this, new send_smsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_postalcode_count", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_postalcode_count")]
    public int sms_postalcode_count(int postalcode, string ostan) {
        object[] results = this.Invoke("sms_postalcode_count", new object[] {
                    postalcode,
                    ostan});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_postalcode_count(int postalcode, string ostan, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_postalcode_count", new object[] {
                    postalcode,
                    ostan}, callback, asyncState);
    }
    
    /// <remarks/>
    public int Endsms_postalcode_count(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void sms_postalcode_countAsync(int postalcode, string ostan) {
        this.sms_postalcode_countAsync(postalcode, ostan, null);
    }
    
    /// <remarks/>
    public void sms_postalcode_countAsync(int postalcode, string ostan, object userState) {
        if ((this.sms_postalcode_countOperationCompleted == null)) {
            this.sms_postalcode_countOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_postalcode_countOperationCompleted);
        }
        this.InvokeAsync("sms_postalcode_count", new object[] {
                    postalcode,
                    ostan}, this.sms_postalcode_countOperationCompleted, userState);
    }
    
    private void Onsms_postalcode_countOperationCompleted(object arg) {
        if ((this.sms_postalcode_countCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_postalcode_countCompleted(this, new sms_postalcode_countCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#is_number_in_blacklist", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("is_number_in_blacklist")]
    public int is_number_in_blacklist(string number) {
        object[] results = this.Invoke("is_number_in_blacklist", new object[] {
                    number});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginis_number_in_blacklist(string number, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("is_number_in_blacklist", new object[] {
                    number}, callback, asyncState);
    }
    
    /// <remarks/>
    public int Endis_number_in_blacklist(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void is_number_in_blacklistAsync(string number) {
        this.is_number_in_blacklistAsync(number, null);
    }
    
    /// <remarks/>
    public void is_number_in_blacklistAsync(string number, object userState) {
        if ((this.is_number_in_blacklistOperationCompleted == null)) {
            this.is_number_in_blacklistOperationCompleted = new System.Threading.SendOrPostCallback(this.Onis_number_in_blacklistOperationCompleted);
        }
        this.InvokeAsync("is_number_in_blacklist", new object[] {
                    number}, this.is_number_in_blacklistOperationCompleted, userState);
    }
    
    private void Onis_number_in_blacklistOperationCompleted(object arg) {
        if ((this.is_number_in_blacklistCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.is_number_in_blacklistCompleted(this, new is_number_in_blacklistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_credit", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_credit")]
    public int sms_credit(string username, string password) {
        object[] results = this.Invoke("sms_credit", new object[] {
                    username,
                    password});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_credit(string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_credit", new object[] {
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public int Endsms_credit(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void sms_creditAsync(string username, string password) {
        this.sms_creditAsync(username, password, null);
    }
    
    /// <remarks/>
    public void sms_creditAsync(string username, string password, object userState) {
        if ((this.sms_creditOperationCompleted == null)) {
            this.sms_creditOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_creditOperationCompleted);
        }
        this.InvokeAsync("sms_credit", new object[] {
                    username,
                    password}, this.sms_creditOperationCompleted, userState);
    }
    
    private void Onsms_creditOperationCompleted(object arg) {
        if ((this.sms_creditCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_creditCompleted(this, new sms_creditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_user_info", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_user_info")]
    public string sms_user_info(string username, string password) {
        object[] results = this.Invoke("sms_user_info", new object[] {
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_user_info(string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_user_info", new object[] {
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_user_info(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_user_infoAsync(string username, string password) {
        this.sms_user_infoAsync(username, password, null);
    }
    
    /// <remarks/>
    public void sms_user_infoAsync(string username, string password, object userState) {
        if ((this.sms_user_infoOperationCompleted == null)) {
            this.sms_user_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_user_infoOperationCompleted);
        }
        this.InvokeAsync("sms_user_info", new object[] {
                    username,
                    password}, this.sms_user_infoOperationCompleted, userState);
    }
    
    private void Onsms_user_infoOperationCompleted(object arg) {
        if ((this.sms_user_infoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_user_infoCompleted(this, new sms_user_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_deliver", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_deliver")]
    public string sms_deliver(string smsid) {
        object[] results = this.Invoke("sms_deliver", new object[] {
                    smsid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_deliver(string smsid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_deliver", new object[] {
                    smsid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_deliver(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_deliverAsync(string smsid) {
        this.sms_deliverAsync(smsid, null);
    }
    
    /// <remarks/>
    public void sms_deliverAsync(string smsid, object userState) {
        if ((this.sms_deliverOperationCompleted == null)) {
            this.sms_deliverOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_deliverOperationCompleted);
        }
        this.InvokeAsync("sms_deliver", new object[] {
                    smsid}, this.sms_deliverOperationCompleted, userState);
    }
    
    private void Onsms_deliverOperationCompleted(object arg) {
        if ((this.sms_deliverCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_deliverCompleted(this, new sms_deliverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_deliver_with_array_of_smsid", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_deliver_with_array_of_smsid")]
    public string sms_deliver_with_array_of_smsid(string smsid_arr, int dargah) {
        object[] results = this.Invoke("sms_deliver_with_array_of_smsid", new object[] {
                    smsid_arr,
                    dargah});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_deliver_with_array_of_smsid(string smsid_arr, int dargah, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_deliver_with_array_of_smsid", new object[] {
                    smsid_arr,
                    dargah}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_deliver_with_array_of_smsid(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_deliver_with_array_of_smsidAsync(string smsid_arr, int dargah) {
        this.sms_deliver_with_array_of_smsidAsync(smsid_arr, dargah, null);
    }
    
    /// <remarks/>
    public void sms_deliver_with_array_of_smsidAsync(string smsid_arr, int dargah, object userState) {
        if ((this.sms_deliver_with_array_of_smsidOperationCompleted == null)) {
            this.sms_deliver_with_array_of_smsidOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_deliver_with_array_of_smsidOperationCompleted);
        }
        this.InvokeAsync("sms_deliver_with_array_of_smsid", new object[] {
                    smsid_arr,
                    dargah}, this.sms_deliver_with_array_of_smsidOperationCompleted, userState);
    }
    
    private void Onsms_deliver_with_array_of_smsidOperationCompleted(object arg) {
        if ((this.sms_deliver_with_array_of_smsidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_deliver_with_array_of_smsidCompleted(this, new sms_deliver_with_array_of_smsidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_deliver_with_deliver_state", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_deliver_with_deliver_state")]
    public string sms_deliver_with_deliver_state(int userid, int deliver_state, int start_from_smsid, int perpage, int dargah) {
        object[] results = this.Invoke("sms_deliver_with_deliver_state", new object[] {
                    userid,
                    deliver_state,
                    start_from_smsid,
                    perpage,
                    dargah});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_deliver_with_deliver_state(int userid, int deliver_state, int start_from_smsid, int perpage, int dargah, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_deliver_with_deliver_state", new object[] {
                    userid,
                    deliver_state,
                    start_from_smsid,
                    perpage,
                    dargah}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_deliver_with_deliver_state(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_deliver_with_deliver_stateAsync(int userid, int deliver_state, int start_from_smsid, int perpage, int dargah) {
        this.sms_deliver_with_deliver_stateAsync(userid, deliver_state, start_from_smsid, perpage, dargah, null);
    }
    
    /// <remarks/>
    public void sms_deliver_with_deliver_stateAsync(int userid, int deliver_state, int start_from_smsid, int perpage, int dargah, object userState) {
        if ((this.sms_deliver_with_deliver_stateOperationCompleted == null)) {
            this.sms_deliver_with_deliver_stateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_deliver_with_deliver_stateOperationCompleted);
        }
        this.InvokeAsync("sms_deliver_with_deliver_state", new object[] {
                    userid,
                    deliver_state,
                    start_from_smsid,
                    perpage,
                    dargah}, this.sms_deliver_with_deliver_stateOperationCompleted, userState);
    }
    
    private void Onsms_deliver_with_deliver_stateOperationCompleted(object arg) {
        if ((this.sms_deliver_with_deliver_stateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_deliver_with_deliver_stateCompleted(this, new sms_deliver_with_deliver_stateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_add_number", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_add_number")]
    public string sms_add_number(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en) {
        object[] results = this.Invoke("sms_add_number", new object[] {
                    username,
                    password,
                    fullname,
                    number,
                    catid,
                    gender,
                    fullname_en,
                    gender_en});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_add_number(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_add_number", new object[] {
                    username,
                    password,
                    fullname,
                    number,
                    catid,
                    gender,
                    fullname_en,
                    gender_en}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_add_number(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_add_numberAsync(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en) {
        this.sms_add_numberAsync(username, password, fullname, number, catid, gender, fullname_en, gender_en, null);
    }
    
    /// <remarks/>
    public void sms_add_numberAsync(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en, object userState) {
        if ((this.sms_add_numberOperationCompleted == null)) {
            this.sms_add_numberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_add_numberOperationCompleted);
        }
        this.InvokeAsync("sms_add_number", new object[] {
                    username,
                    password,
                    fullname,
                    number,
                    catid,
                    gender,
                    fullname_en,
                    gender_en}, this.sms_add_numberOperationCompleted, userState);
    }
    
    private void Onsms_add_numberOperationCompleted(object arg) {
        if ((this.sms_add_numberCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_add_numberCompleted(this, new sms_add_numberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_receive_list", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_receive_list")]
    public string sms_receive_list(string username, string password, string number, int catid, int start, int perpage, int read, string order) {
        object[] results = this.Invoke("sms_receive_list", new object[] {
                    username,
                    password,
                    number,
                    catid,
                    start,
                    perpage,
                    read,
                    order});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_receive_list(string username, string password, string number, int catid, int start, int perpage, int read, string order, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_receive_list", new object[] {
                    username,
                    password,
                    number,
                    catid,
                    start,
                    perpage,
                    read,
                    order}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_receive_list(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_receive_listAsync(string username, string password, string number, int catid, int start, int perpage, int read, string order) {
        this.sms_receive_listAsync(username, password, number, catid, start, perpage, read, order, null);
    }
    
    /// <remarks/>
    public void sms_receive_listAsync(string username, string password, string number, int catid, int start, int perpage, int read, string order, object userState) {
        if ((this.sms_receive_listOperationCompleted == null)) {
            this.sms_receive_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_receive_listOperationCompleted);
        }
        this.InvokeAsync("sms_receive_list", new object[] {
                    username,
                    password,
                    number,
                    catid,
                    start,
                    perpage,
                    read,
                    order}, this.sms_receive_listOperationCompleted, userState);
    }
    
    private void Onsms_receive_listOperationCompleted(object arg) {
        if ((this.sms_receive_listCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_receive_listCompleted(this, new sms_receive_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_receive_list_array", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_receive_list_array")]
    public string sms_receive_list_array(string username, string password, string number, int catid, int start, int perpage, int read, string order) {
        object[] results = this.Invoke("sms_receive_list_array", new object[] {
                    username,
                    password,
                    number,
                    catid,
                    start,
                    perpage,
                    read,
                    order});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_receive_list_array(string username, string password, string number, int catid, int start, int perpage, int read, string order, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_receive_list_array", new object[] {
                    username,
                    password,
                    number,
                    catid,
                    start,
                    perpage,
                    read,
                    order}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_receive_list_array(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_receive_list_arrayAsync(string username, string password, string number, int catid, int start, int perpage, int read, string order) {
        this.sms_receive_list_arrayAsync(username, password, number, catid, start, perpage, read, order, null);
    }
    
    /// <remarks/>
    public void sms_receive_list_arrayAsync(string username, string password, string number, int catid, int start, int perpage, int read, string order, object userState) {
        if ((this.sms_receive_list_arrayOperationCompleted == null)) {
            this.sms_receive_list_arrayOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_receive_list_arrayOperationCompleted);
        }
        this.InvokeAsync("sms_receive_list_array", new object[] {
                    username,
                    password,
                    number,
                    catid,
                    start,
                    perpage,
                    read,
                    order}, this.sms_receive_list_arrayOperationCompleted, userState);
    }
    
    private void Onsms_receive_list_arrayOperationCompleted(object arg) {
        if ((this.sms_receive_list_arrayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_receive_list_arrayCompleted(this, new sms_receive_list_arrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_receive_change_read", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_receive_change_read")]
    public string sms_receive_change_read(string username, string password, int id, int read) {
        object[] results = this.Invoke("sms_receive_change_read", new object[] {
                    username,
                    password,
                    id,
                    read});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_receive_change_read(string username, string password, int id, int read, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_receive_change_read", new object[] {
                    username,
                    password,
                    id,
                    read}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_receive_change_read(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_receive_change_readAsync(string username, string password, int id, int read) {
        this.sms_receive_change_readAsync(username, password, id, read, null);
    }
    
    /// <remarks/>
    public void sms_receive_change_readAsync(string username, string password, int id, int read, object userState) {
        if ((this.sms_receive_change_readOperationCompleted == null)) {
            this.sms_receive_change_readOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_receive_change_readOperationCompleted);
        }
        this.InvokeAsync("sms_receive_change_read", new object[] {
                    username,
                    password,
                    id,
                    read}, this.sms_receive_change_readOperationCompleted, userState);
    }
    
    private void Onsms_receive_change_readOperationCompleted(object arg) {
        if ((this.sms_receive_change_readCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_receive_change_readCompleted(this, new sms_receive_change_readCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#add_user", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("add_user")]
    public string add_user(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid) {
        object[] results = this.Invoke("add_user", new object[] {
                    admin_username,
                    admin_password,
                    username,
                    password,
                    email,
                    fullname,
                    mobile,
                    catid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginadd_user(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("add_user", new object[] {
                    admin_username,
                    admin_password,
                    username,
                    password,
                    email,
                    fullname,
                    mobile,
                    catid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endadd_user(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void add_userAsync(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid) {
        this.add_userAsync(admin_username, admin_password, username, password, email, fullname, mobile, catid, null);
    }
    
    /// <remarks/>
    public void add_userAsync(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid, object userState) {
        if ((this.add_userOperationCompleted == null)) {
            this.add_userOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_userOperationCompleted);
        }
        this.InvokeAsync("add_user", new object[] {
                    admin_username,
                    admin_password,
                    username,
                    password,
                    email,
                    fullname,
                    mobile,
                    catid}, this.add_userOperationCompleted, userState);
    }
    
    private void Onadd_userOperationCompleted(object arg) {
        if ((this.add_userCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.add_userCompleted(this, new add_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_send_bulk_5000", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_send_bulk_5000")]
    public string sms_send_bulk_5000(string username, string password, string sender_number, int bankid, string note, string date, string record_start, string receiver_count, int gender, int receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, string billing_title, string request_uniqueid) {
        object[] results = this.Invoke("sms_send_bulk_5000", new object[] {
                    username,
                    password,
                    sender_number,
                    bankid,
                    note,
                    date,
                    record_start,
                    receiver_count,
                    gender,
                    receiver_number_kind,
                    age_start,
                    age_end,
                    receiver_number_perfix,
                    billing_title,
                    request_uniqueid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_send_bulk_5000(
                string username, 
                string password, 
                string sender_number, 
                int bankid, 
                string note, 
                string date, 
                string record_start, 
                string receiver_count, 
                int gender, 
                int receiver_number_kind, 
                int age_start, 
                int age_end, 
                int receiver_number_perfix, 
                string billing_title, 
                string request_uniqueid, 
                System.AsyncCallback callback, 
                object asyncState) {
        return this.BeginInvoke("sms_send_bulk_5000", new object[] {
                    username,
                    password,
                    sender_number,
                    bankid,
                    note,
                    date,
                    record_start,
                    receiver_count,
                    gender,
                    receiver_number_kind,
                    age_start,
                    age_end,
                    receiver_number_perfix,
                    billing_title,
                    request_uniqueid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_send_bulk_5000(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_send_bulk_5000Async(string username, string password, string sender_number, int bankid, string note, string date, string record_start, string receiver_count, int gender, int receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, string billing_title, string request_uniqueid) {
        this.sms_send_bulk_5000Async(username, password, sender_number, bankid, note, date, record_start, receiver_count, gender, receiver_number_kind, age_start, age_end, receiver_number_perfix, billing_title, request_uniqueid, null);
    }
    
    /// <remarks/>
    public void sms_send_bulk_5000Async(
                string username, 
                string password, 
                string sender_number, 
                int bankid, 
                string note, 
                string date, 
                string record_start, 
                string receiver_count, 
                int gender, 
                int receiver_number_kind, 
                int age_start, 
                int age_end, 
                int receiver_number_perfix, 
                string billing_title, 
                string request_uniqueid, 
                object userState) {
        if ((this.sms_send_bulk_5000OperationCompleted == null)) {
            this.sms_send_bulk_5000OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_send_bulk_5000OperationCompleted);
        }
        this.InvokeAsync("sms_send_bulk_5000", new object[] {
                    username,
                    password,
                    sender_number,
                    bankid,
                    note,
                    date,
                    record_start,
                    receiver_count,
                    gender,
                    receiver_number_kind,
                    age_start,
                    age_end,
                    receiver_number_perfix,
                    billing_title,
                    request_uniqueid}, this.sms_send_bulk_5000OperationCompleted, userState);
    }
    
    private void Onsms_send_bulk_5000OperationCompleted(object arg) {
        if ((this.sms_send_bulk_5000Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_send_bulk_5000Completed(this, new sms_send_bulk_5000CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_count_bulk_5000", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_count_bulk_5000")]
    public string sms_count_bulk_5000(int bankid, int gender, int receiver_number_kind, int age_start, int age_end, int receiver_number_perfix) {
        object[] results = this.Invoke("sms_count_bulk_5000", new object[] {
                    bankid,
                    gender,
                    receiver_number_kind,
                    age_start,
                    age_end,
                    receiver_number_perfix});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_count_bulk_5000(int bankid, int gender, int receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_count_bulk_5000", new object[] {
                    bankid,
                    gender,
                    receiver_number_kind,
                    age_start,
                    age_end,
                    receiver_number_perfix}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_count_bulk_5000(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_count_bulk_5000Async(int bankid, int gender, int receiver_number_kind, int age_start, int age_end, int receiver_number_perfix) {
        this.sms_count_bulk_5000Async(bankid, gender, receiver_number_kind, age_start, age_end, receiver_number_perfix, null);
    }
    
    /// <remarks/>
    public void sms_count_bulk_5000Async(int bankid, int gender, int receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, object userState) {
        if ((this.sms_count_bulk_5000OperationCompleted == null)) {
            this.sms_count_bulk_5000OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_count_bulk_5000OperationCompleted);
        }
        this.InvokeAsync("sms_count_bulk_5000", new object[] {
                    bankid,
                    gender,
                    receiver_number_kind,
                    age_start,
                    age_end,
                    receiver_number_perfix}, this.sms_count_bulk_5000OperationCompleted, userState);
    }
    
    private void Onsms_count_bulk_5000OperationCompleted(object arg) {
        if ((this.sms_count_bulk_5000Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_count_bulk_5000Completed(this, new sms_count_bulk_5000CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:sms_webservice#sms_webservice#sms_count_bank_5000", RequestNamespace="urn:sms_webservice", ResponseNamespace="urn:sms_webservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("sms_count_bank_5000")]
    public string sms_count_bank_5000(int parentid) {
        object[] results = this.Invoke("sms_count_bank_5000", new object[] {
                    parentid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsms_count_bank_5000(int parentid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sms_count_bank_5000", new object[] {
                    parentid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endsms_count_bank_5000(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sms_count_bank_5000Async(int parentid) {
        this.sms_count_bank_5000Async(parentid, null);
    }
    
    /// <remarks/>
    public void sms_count_bank_5000Async(int parentid, object userState) {
        if ((this.sms_count_bank_5000OperationCompleted == null)) {
            this.sms_count_bank_5000OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_count_bank_5000OperationCompleted);
        }
        this.InvokeAsync("sms_count_bank_5000", new object[] {
                    parentid}, this.sms_count_bank_5000OperationCompleted, userState);
    }
    
    private void Onsms_count_bank_5000OperationCompleted(object arg) {
        if ((this.sms_count_bank_5000Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sms_count_bank_5000Completed(this, new sms_count_bank_5000CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_get_number_in_catCompletedEventHandler(object sender, sms_get_number_in_catCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_get_number_in_catCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_get_number_in_catCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_get_cat_listCompletedEventHandler(object sender, sms_get_cat_listCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_get_cat_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_get_cat_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void send_sms_all_arrayCompletedEventHandler(object sender, send_sms_all_arrayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class send_sms_all_arrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal send_sms_all_arrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void send_sms_arrayCompletedEventHandler(object sender, send_sms_arrayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class send_sms_arrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal send_sms_arrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void send_smsCompletedEventHandler(object sender, send_smsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class send_smsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal send_smsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_postalcode_countCompletedEventHandler(object sender, sms_postalcode_countCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_postalcode_countCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_postalcode_countCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void is_number_in_blacklistCompletedEventHandler(object sender, is_number_in_blacklistCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class is_number_in_blacklistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal is_number_in_blacklistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_creditCompletedEventHandler(object sender, sms_creditCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_creditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_creditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_user_infoCompletedEventHandler(object sender, sms_user_infoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_user_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_user_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_deliverCompletedEventHandler(object sender, sms_deliverCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_deliverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_deliverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_deliver_with_array_of_smsidCompletedEventHandler(object sender, sms_deliver_with_array_of_smsidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_deliver_with_array_of_smsidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_deliver_with_array_of_smsidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_deliver_with_deliver_stateCompletedEventHandler(object sender, sms_deliver_with_deliver_stateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_deliver_with_deliver_stateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_deliver_with_deliver_stateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_add_numberCompletedEventHandler(object sender, sms_add_numberCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_add_numberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_add_numberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_receive_listCompletedEventHandler(object sender, sms_receive_listCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_receive_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_receive_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_receive_list_arrayCompletedEventHandler(object sender, sms_receive_list_arrayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_receive_list_arrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_receive_list_arrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_receive_change_readCompletedEventHandler(object sender, sms_receive_change_readCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_receive_change_readCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_receive_change_readCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void add_userCompletedEventHandler(object sender, add_userCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class add_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal add_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_send_bulk_5000CompletedEventHandler(object sender, sms_send_bulk_5000CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_send_bulk_5000CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_send_bulk_5000CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_count_bulk_5000CompletedEventHandler(object sender, sms_count_bulk_5000CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_count_bulk_5000CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_count_bulk_5000CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sms_count_bank_5000CompletedEventHandler(object sender, sms_count_bank_5000CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sms_count_bank_5000CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sms_count_bank_5000CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
